name: Build ESP32 Firmware

on:
  push:
    branches: [ develop ]
  pull_request:
  workflow_dispatch: 
jobs:
  build-esp32:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          # Додаємо URL для esp32, інакше core install не знайде пакет
          ./bin/arduino-cli config init
          ./bin/arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core install esp32:esp32

      - name: Compile firmware
        run: |
          curl -fsSL https://raw.githubusercontent.com | sh
          # Ініціалізуємо конфіг ОДРАЗУ з потрібною URL-адресою, 
          # щоб уникнути появи порожніх значень
          ./bin/arduino-cli config init --additional-urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json --overwrite
          
          # Оновлюємо індекси (тепер URL вже в конфігу)
          ./bin/arduino-cli core update-index
          ./bin/arduino-cli core install esp32:esp32

      - name: Upload compiled firmware
        uses: actions/upload-artifact@v4
        with:
          name: esp32-firmware-bin
          # Використовуємо конкретний шлях до створеної папки
          path: build_output/*.bin
